language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

script:
  - ./go.test.sh
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)
